In [1]:
import numpy as np

In [3]:
arr1=np.arange(8).reshape(2,4)
arr2=np.arange(8,16).reshape(2,4)

In [4]:
arr1+arr2 #we know similar size array would easily perform addition operation

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [8]:
arr3=np.arange(8).reshape(2,4)
arr4=np.arange(8,12).reshape(1,4)
print(arr3)
print(arr4)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]]


In [9]:
arr3+arr4 #as you can see shape of array is not same even though arthematic operation is possible why?   #because of braodcasting

array([[ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [10]:
#if you have two differet shape ,addition can be possible between them but it has to fullfill some condition
#check the element dimension size is the number equal or one of them is one for each dimension of array then broadcast is possible 
#if not then broadcast is not possible and it will lead to an error

In [12]:
arr6 = np.arange(8).reshape(2,4)
arr7=np.arange(8,16).reshape(4,2)
print(arr6)
print(arr7)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [ ]:
arr6+arr7 #this will give error because if you compare dimensions of them they are not full filling the condition
#arr6(2,4)
#arr(4,2)   #4!=2 or niether one of them is 1 same for other dimesion 
            #2!=