In [1]:
import numpy as np

In [2]:
arr1=np.arange(24).reshape(6,4)

In [3]:
print(arr1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [4]:
arr1([0,2,4])

TypeError: 'numpy.ndarray' object is not callable