In [1]:
import numpy as np

In [3]:
#lets generate a random array using random 
arr1=np.random.randint(low=1,high=100,size=20).reshape(4,5)
print(arr1)

[[37 97 53 32 23]
 [45 93 11 31 77]
 [48 34  2 68 55]
 [11 44 80 44 41]]


In [13]:
arr1[0 ][1]

97

In [9]:
arr1[0,1]

97

In [15]:
arr1>50 #it will return an boolean array mean every element of this array is boolean

array([[False,  True,  True, False, False],
       [False,  True, False, False,  True],
       [False, False, False,  True,  True],
       [False, False,  True, False, False]])

In [16]:
#but if we want array of thise element which is greater thann 50
#then we use indexing using boolean arrays /filtering

arr1[arr1>50]   #its very scalable


array([97, 53, 93, 77, 68, 55, 80])

In [20]:
#we can give condition more than one 
arr1[(arr1>50) & (arr1%2!=0)]  #we can use here'and' because both condition give boolean value so that's why bitwise &(and)

array([97, 53, 93, 77, 55])

In [21]:
#if we want to change these into zero(0)
#we can
arr1[(arr1>50) & (arr1%2!=0)] =0

In [22]:
print(arr1) #you can see here the zeros in array

[[37  0  0 32 23]
 [45  0 11 31  0]
 [48 34  2 68  0]
 [11 44 80 44 41]]
