In [1]:
import numpy as np

In [4]:
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [7]:
arr2=np.array([[1,2,3],[1,2,3]])
print(arr2)

[[1 2 3]
 [1 2 3]]


In [9]:
arr3=np.arange(24)
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [11]:
arr4=arr3.reshape(6,4)#this function used to resape one array to another carefull check the number of element must be
                      #equal of the matrix
print(arr4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [12]:
arr4[0] #it will return first row index=0

array([0, 1, 2, 3])

In [17]:
#if i want a perticular elemnt
arr4[2,3] #it,s called indexing beacuse we are extrating single element


11

In [21]:
#to access 3rd column
arr4[:,3]     #colon is used to decide staring and ending point of row or column like 2:4 mean 2nd and 3rd row will print 
              #it's like the we are giving the range to row and column

array([ 3,  7, 11, 15, 19, 23])

In [24]:
arr4[2:4]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
arr4[2:4,2:4] #we applied  range in both row and column

array([[10, 11],
       [14, 15]])

In [26]:
arr4[2:4,1:3] #this opration is called slicing because we are extracting multiple items

array([[ 9, 10],
       [13, 14]])

In [27]:
#lets talk about the iteration 
for i in arr4: #it will print every row #it will iterate through each row
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [31]:
#if we have to iterate through each element 
for i in np.nditer(arr4):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [ ]:
#end