In [2]:
import numpy as np

In [4]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

In [5]:
arr3=np.arange(6).reshape(3,2)
arr4=np.arange(6,12).reshape(2,3)


In [6]:
print(arr3)

[[0 1]
 [2 3]
 [4 5]]


In [7]:
print(arr4)

[[ 6  7  8]
 [ 9 10 11]]


In [12]:
arr4.ravel() #it coverts n-d arrays into 1-d array


array([ 6,  7,  8,  9, 10, 11])

In [11]:
arr3.ravel()

array([0, 1, 2, 3, 4, 5])

In [14]:
arr3

array([[0, 1],
       [2, 3],
       [4, 5]])

In [21]:
arr5=arr3.transpose()
print(arr5)#convert row to column and column to row that is called transpose of matrix

[[0 2 4]
 [1 3 5]]


In [22]:
arr5

array([[0, 2, 4],
       [1, 3, 5]])

In [24]:
np.hstack((arr4,arr5)) #it takes a tuble of arrays as input and hstack ,stack the arrys horizontaly
                       #rows of the arrays must be same for horizontal stacking

array([[ 6,  7,  8,  0,  2,  4],
       [ 9, 10, 11,  1,  3,  5]])

In [27]:
arr3

array([[0, 1],
       [2, 3],
       [4, 5]])

In [29]:
arr6=np.arange(12,18).reshape(3,2)
arr6

array([[12, 13],
       [14, 15],
       [16, 17]])

In [31]:
#column must be sam efor vertival satcking
arr7=np.vstack((arr3,arr6)) #mean same column or row element join and for a big column or row on same position
print(arr7)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [12 13]
 [14 15]
 [16 17]]


In [38]:
print(np.hsplit(arr7,2)) #for horizontally split the table #it split by column wise mean hrizontally if you think more you will understand
#given 2 because it has 2 column or it can devide in two qual parts on horizontal axis

[array([[ 0],
       [ 2],
       [ 4],
       [12],
       [14],
       [16]]), array([[ 1],
       [ 3],
       [ 5],
       [13],
       [15],
       [17]])]


In [39]:
arr3

array([[0, 1],
       [2, 3],
       [4, 5]])

In [40]:
np.vsplit(arr3,3) #give 3 because it can split vertically in three eqaul parts

[array([[0, 1]]), array([[2, 3]]), array([[4, 5]])]

In [ ]:
#day3 end