In [1]:
#NUMPY ATTRIBUTES
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)
arr1

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [6]:
#leats create a 2d and 3d array
arr2=np.array([[1,2,3,4,5],[6,7,8,9,0]])#hint-in 2-d arrays we make list of 1-d arrays
print("this is 2d array:",arr2)
arr2
arr3=np.array([[[2,3],[1,2]],[[1,2],[4,5]],[[3,4],[6,7]]])#hint-in 3d-array we make list of 2-d arrays 
print("This is 3d array:",arr3)
arr3

this is 2d array: [[1 2 3 4 5]
 [6 7 8 9 0]]
This is 3d array: [[[2 3]
  [1 2]]

 [[1 2]
  [4 5]]

 [[3 4]
  [6 7]]]


array([[[2, 3],
        [1, 2]],

       [[1, 2],
        [4, 5]],

       [[3, 4],
        [6, 7]]])

In [7]:
#one more function which we can access to know the dimension of our array 

arr2.ndim #you can writ et like this also 'np.ndim(arr2)'

2

In [8]:
arr2.ndim

2

In [17]:

np.ndim(arr3)

3

In [10]:
arr4=np.linspace(10,20,10)
print(arr4)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [11]:
#some new functions
np.size(arr2)  #it will return the number of items or number of values



10

In [12]:
np.array(arr1)

array([1, 2, 3, 4, 5])

In [13]:
np.size(arr1)

5

In [18]:
np.ndim(arr4)

1

In [20]:
arr1.itemsize

4

In [22]:
arr4.itemsize #we can not write it like this because it is an attribute not function np.itemsize(arr4)
#gives because values inside arr4 is float

8

In [24]:
arr1.dtype #to knoew the datatype of array

dtype('int32')

In [25]:
arr4.dtype

dtype('float64')

In [26]:
arr4.astype(int) #convert one datatype of an array from one to another 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 20])