In [1]:
import numpy as np

In [26]:
np.random.random() #The np.random.random() function in NumPy generates random floats between 0.0 and 1.0 (excluding 1.0)

0.9133663418130602

In [27]:
np.random.random((2,3))         # Generate a 2x3 array of random numbers

array([[0.12135616, 0.75022318, 0.16835902],
       [0.80427997, 0.89437053, 0.12461273]])

np.random.random(5)

In [28]:
np.random.random(5)          #generate a 1-d array of 5 elements

array([0.90569632, 0.52606496, 0.66085817, 0.36611179, 0.20396843])

In [29]:
np.random.random(6).reshape(3,2)

array([[0.57422937, 0.13690951],
       [0.99884442, 0.25926788],
       [0.87251318, 0.66534196]])

In [34]:
if np.random.random() < 0.3:  # 30% probability
    print("Event occurred!")
else:
    print("event is not occurred")

event is not occurred


In [42]:
#if you want same number everytime use seed() funtion
np.random.seed(23)#you can change parameter number inside seed according to that random number also changes
np.random.random()

0.5172978838465893

In [44]:
np.random.random()

0.7654597593969069

In [45]:
np.random.random((2,3,4)) #it will give an 3-d array

array([[[2.82395844e-01, 2.21045363e-01, 6.86222085e-01, 1.67139203e-01],
        [3.92442466e-01, 6.18052347e-01, 4.11930095e-01, 2.46488120e-03],
        [8.84032182e-01, 8.84947538e-01, 3.00409689e-01, 5.89581865e-01]],

       [[9.78426916e-01, 8.45093822e-01, 6.50754391e-02, 2.94744465e-01],
        [2.87934441e-01, 8.22466339e-01, 6.26183038e-01, 1.10477714e-01],
        [5.28811169e-04, 9.42166233e-01, 1.41500758e-01, 4.21596526e-01]]])

In [48]:
#np.random.uniform(low=0.0, high=1.0, size=None)

np.random.uniform(1,10) #it will generate the random number between the 1 to 10 everytime ,np.random.uniform(low=0.0, high=10.0)
                    

2.4581123110247405

In [59]:
np.random.uniform(0,10,10)#np.random.random(0,10,size=10)

array([9.55739841, 9.01602193, 5.05759322, 8.20701485, 8.27715926,
       2.31833348, 0.79055486, 4.65762926, 8.78975808, 1.47503059])

In [67]:
#if you want to generate int value instead of float use (randint())
#np.random.randint(low, high=None, size=None, dtype=int) none means they are optional

np.random.randint(10) #10 is exclusive here 10 is high

0

In [78]:
arr1=np.random.randint(1, high=10, size=10, dtype=int)
arr1

array([8, 3, 1, 4, 8, 5, 9, 2, 9, 2])

In [75]:
np.random.randint(1, high=10, size=10, dtype=int).reshape(2,5) #dtype =int32 or int 64

array([[2, 6, 1, 7, 5],
       [8, 7, 3, 8, 7]])

In [74]:
# 2D array of shape (2, 3) with random ints from 10 to 20
np.random.randint(10, 20, size=(2, 3))

array([[10, 12, 12],
       [16, 12, 18]])

In [82]:
arr1

array([8, 3, 1, 4, 8, 5, 9, 2, 9, 2])

In [80]:
np.max(arr1) #arr1.max()

9

In [81]:
#if we have to find out index of max number in array
np.argmax(arr1)

6

In [83]:
np.argmin(arr1) #for min values's index

2

In [84]:
arr1[np.argmin(arr1)] #you can print the minimum number

1

In [85]:
arr1

array([8, 3, 1, 4, 8, 5, 9, 2, 9, 2])

In [94]:
#if you want to change the odd value to -1
arr1[arr1%2!=0]=-1 #it's called boolean indexing (also known as mask-based indexing).
                   #internally here runs a where fuction which return a array of indexes where the condition is true
                   #you can see a example below of where 
arr1

array([-1, 10, -1, 14, -1, -1, 18,  2, 10,  4])

In [97]:
arr1=np.random.randint(1,20,10)
arr1

array([14, 19, 17,  3,  4,  4, 13,  6, 18,  1])

In [98]:
np.where((arr1%2)!=0) #it returns the index of odd numbers or where the condition is true

(array([1, 2, 3, 6, 9], dtype=int64),)

In [100]:
index_array=np.where((arr1%2)!=0)
print(arr1[index_array]) #print those odd numbers

[19 17  3 13  1]


In [101]:
#full syntax of where function  
#np.where(condition, value_if_true, value_if_false)
arr1

array([14, 19, 17,  3,  4,  4, 13,  6, 18,  1])

In [102]:
np.where(arr1%2!=0,-1,1) #odd=-1 and even =1 #but it will not change the actual array

array([ 1, -1, -1, -1,  1,  1, -1,  1,  1, -1])

In [103]:
arr1 #you can see that actual array butif you use boolean indexing it will changeg original array

array([14, 19, 17,  3,  4,  4, 13,  6, 18,  1])

In [106]:
#if you dont want to change the even value
np.where(arr1%2!=0,-1,arr1)

array([14, -1, -1, -1,  4,  4, -1,  6, 18, -1])

In [107]:
#lets understand one more function that is percentile not percentage 
arr1

array([14, 19, 17,  3,  4,  4, 13,  6, 18,  1])

In [108]:
print(np.percentile(arr1,50)) #it means that 9.5 is the value greater than the 50% elements of the arr1

9.5


In [117]:
#percentile we here in exams result means we got 90 percentile means we have scored higher than the 90 percente of the people who appear in the exam
print(np.percentile(arr1,25)) #4 is greater thann 25 percent values of arr1

4.0


In [ ]:
#if array is 2-d we can also find it for row and column seprately using axis=1(row) and 0(column)
#np.percentile(arr2,25,axis=1)

In [125]:
#how to sort array
arr2=np.random.randint(1,10,10)
print(" before sorting",arr2)
a=np.sort(arr2)#it will not make changes in arr2
print(a)
print("after sorting:",arr2)

 before sorting [9 7 7 8 4 8 7 5 4 4]
[4 4 4 5 7 7 7 8 8 9]
after sorting: [9 7 7 8 4 8 7 5 4 4]


In [126]:
print("before",arr2)
arr2.sort()#but this will change the arr2
print("after",arr2)


before [9 7 7 8 4 8 7 5 4 4]
after [4 4 4 5 7 7 7 8 8 9]
